// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockmikrotik

import (
	mikrotik "github.com/jtdoepke/amp-mikrotik-port-forwarder/internal/mikrotik"
	mock "github.com/stretchr/testify/mock"
)

// MockRouterClient is an autogenerated mock type for the RouterClient type
type MockRouterClient struct {
	mock.Mock
}

type MockRouterClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRouterClient) EXPECT() *MockRouterClient_Expecter {
	return &MockRouterClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockRouterClient) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRouterClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockRouterClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockRouterClient_Expecter) Close() *MockRouterClient_Close_Call {
	return &MockRouterClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockRouterClient_Close_Call) Run(run func()) *MockRouterClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRouterClient_Close_Call) Return(_a0 error) *MockRouterClient_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRouterClient_Close_Call) RunAndReturn(run func() error) *MockRouterClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRule provides a mock function with given fields: ruleType, rule
func (_m *MockRouterClient) CreateRule(ruleType mikrotik.RuleType, rule mikrotik.Rule) error {
	ret := _m.Called(ruleType, rule)

	if len(ret) == 0 {
		panic("no return value specified for CreateRule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(mikrotik.RuleType, mikrotik.Rule) error); ok {
		r0 = rf(ruleType, rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRouterClient_CreateRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRule'
type MockRouterClient_CreateRule_Call struct {
	*mock.Call
}

// CreateRule is a helper method to define mock.On call
//   - ruleType mikrotik.RuleType
//   - rule mikrotik.Rule
func (_e *MockRouterClient_Expecter) CreateRule(ruleType interface{}, rule interface{}) *MockRouterClient_CreateRule_Call {
	return &MockRouterClient_CreateRule_Call{Call: _e.mock.On("CreateRule", ruleType, rule)}
}

func (_c *MockRouterClient_CreateRule_Call) Run(run func(ruleType mikrotik.RuleType, rule mikrotik.Rule)) *MockRouterClient_CreateRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(mikrotik.RuleType), args[1].(mikrotik.Rule))
	})
	return _c
}

func (_c *MockRouterClient_CreateRule_Call) Return(_a0 error) *MockRouterClient_CreateRule_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRouterClient_CreateRule_Call) RunAndReturn(run func(mikrotik.RuleType, mikrotik.Rule) error) *MockRouterClient_CreateRule_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRule provides a mock function with given fields: ruleType, id
func (_m *MockRouterClient) DeleteRule(ruleType mikrotik.RuleType, id string) error {
	ret := _m.Called(ruleType, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(mikrotik.RuleType, string) error); ok {
		r0 = rf(ruleType, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRouterClient_DeleteRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRule'
type MockRouterClient_DeleteRule_Call struct {
	*mock.Call
}

// DeleteRule is a helper method to define mock.On call
//   - ruleType mikrotik.RuleType
//   - id string
func (_e *MockRouterClient_Expecter) DeleteRule(ruleType interface{}, id interface{}) *MockRouterClient_DeleteRule_Call {
	return &MockRouterClient_DeleteRule_Call{Call: _e.mock.On("DeleteRule", ruleType, id)}
}

func (_c *MockRouterClient_DeleteRule_Call) Run(run func(ruleType mikrotik.RuleType, id string)) *MockRouterClient_DeleteRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(mikrotik.RuleType), args[1].(string))
	})
	return _c
}

func (_c *MockRouterClient_DeleteRule_Call) Return(_a0 error) *MockRouterClient_DeleteRule_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRouterClient_DeleteRule_Call) RunAndReturn(run func(mikrotik.RuleType, string) error) *MockRouterClient_DeleteRule_Call {
	_c.Call.Return(run)
	return _c
}

// FindRuleByComment provides a mock function with given fields: ruleType, chain, comment
func (_m *MockRouterClient) FindRuleByComment(ruleType mikrotik.RuleType, chain string, comment string) (*mikrotik.Rule, error) {
	ret := _m.Called(ruleType, chain, comment)

	if len(ret) == 0 {
		panic("no return value specified for FindRuleByComment")
	}

	var r0 *mikrotik.Rule
	var r1 error
	if rf, ok := ret.Get(0).(func(mikrotik.RuleType, string, string) (*mikrotik.Rule, error)); ok {
		return rf(ruleType, chain, comment)
	}
	if rf, ok := ret.Get(0).(func(mikrotik.RuleType, string, string) *mikrotik.Rule); ok {
		r0 = rf(ruleType, chain, comment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mikrotik.Rule)
		}
	}

	if rf, ok := ret.Get(1).(func(mikrotik.RuleType, string, string) error); ok {
		r1 = rf(ruleType, chain, comment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRouterClient_FindRuleByComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindRuleByComment'
type MockRouterClient_FindRuleByComment_Call struct {
	*mock.Call
}

// FindRuleByComment is a helper method to define mock.On call
//   - ruleType mikrotik.RuleType
//   - chain string
//   - comment string
func (_e *MockRouterClient_Expecter) FindRuleByComment(ruleType interface{}, chain interface{}, comment interface{}) *MockRouterClient_FindRuleByComment_Call {
	return &MockRouterClient_FindRuleByComment_Call{Call: _e.mock.On("FindRuleByComment", ruleType, chain, comment)}
}

func (_c *MockRouterClient_FindRuleByComment_Call) Run(run func(ruleType mikrotik.RuleType, chain string, comment string)) *MockRouterClient_FindRuleByComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(mikrotik.RuleType), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockRouterClient_FindRuleByComment_Call) Return(_a0 *mikrotik.Rule, _a1 error) *MockRouterClient_FindRuleByComment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRouterClient_FindRuleByComment_Call) RunAndReturn(run func(mikrotik.RuleType, string, string) (*mikrotik.Rule, error)) *MockRouterClient_FindRuleByComment_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRule provides a mock function with given fields: ruleType, id, rule
func (_m *MockRouterClient) UpdateRule(ruleType mikrotik.RuleType, id string, rule mikrotik.Rule) error {
	ret := _m.Called(ruleType, id, rule)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(mikrotik.RuleType, string, mikrotik.Rule) error); ok {
		r0 = rf(ruleType, id, rule)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRouterClient_UpdateRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRule'
type MockRouterClient_UpdateRule_Call struct {
	*mock.Call
}

// UpdateRule is a helper method to define mock.On call
//   - ruleType mikrotik.RuleType
//   - id string
//   - rule mikrotik.Rule
func (_e *MockRouterClient_Expecter) UpdateRule(ruleType interface{}, id interface{}, rule interface{}) *MockRouterClient_UpdateRule_Call {
	return &MockRouterClient_UpdateRule_Call{Call: _e.mock.On("UpdateRule", ruleType, id, rule)}
}

func (_c *MockRouterClient_UpdateRule_Call) Run(run func(ruleType mikrotik.RuleType, id string, rule mikrotik.Rule)) *MockRouterClient_UpdateRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(mikrotik.RuleType), args[1].(string), args[2].(mikrotik.Rule))
	})
	return _c
}

func (_c *MockRouterClient_UpdateRule_Call) Return(_a0 error) *MockRouterClient_UpdateRule_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRouterClient_UpdateRule_Call) RunAndReturn(run func(mikrotik.RuleType, string, mikrotik.Rule) error) *MockRouterClient_UpdateRule_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRouterClient creates a new instance of MockRouterClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRouterClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRouterClient {
	mock := &MockRouterClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
