// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockamp

import (
	amp "github.com/jtdoepke/amp-mikrotik-port-forwarder/internal/amp"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockClient) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Close_Call) Return(_a0 error) *MockClient_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func() error) *MockClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstances provides a mock function with no fields
func (_m *MockClient) GetInstances() ([]amp.Instance, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetInstances")
	}

	var r0 []amp.Instance
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]amp.Instance, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []amp.Instance); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]amp.Instance)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetInstances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstances'
type MockClient_GetInstances_Call struct {
	*mock.Call
}

// GetInstances is a helper method to define mock.On call
func (_e *MockClient_Expecter) GetInstances() *MockClient_GetInstances_Call {
	return &MockClient_GetInstances_Call{Call: _e.mock.On("GetInstances")}
}

func (_c *MockClient_GetInstances_Call) Run(run func()) *MockClient_GetInstances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_GetInstances_Call) Return(_a0 []amp.Instance, _a1 error) *MockClient_GetInstances_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetInstances_Call) RunAndReturn(run func() ([]amp.Instance, error)) *MockClient_GetInstances_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
